
import { Metadata } from 'next';
import '@/app/globals.css'
import { DashSideBare } from '@/components/dashboard/DashSideBar';
import { DashHeader } from '@/components/dashboard/DashHeader';
import { Breacramp } from '@/components/dashboard/Breacramp';
export const metadata: Metadata = {
    title: "DashBoard for Doctors",
    description: "Generated by RedHawk",
  };

const layout = ({children}:{children:React.ReactNode}) => {
  return (
    <div className="grid min-h-screen w-full md:grid-cols-[220px_1fr] lg:grid-cols-[280px_1fr]">
      {/* //wh sidbar */}
      <DashSideBare/>
      <div className="flex flex-col">
        {/* //wh header */}
        <DashHeader/>
        <main className="flex flex-1 flex-col gap-4 p-4 lg:gap-6 lg:p-6">
          {/* //wh  breacramp */}
          <Breacramp/>
          {children}
        </main>
      </div>
    </div>
  )
}

export default layout